#ifndef NEURAL_NETWORK_H
#define NEURAL_NETWORK_H

// Generated by indiflight_module/Generate_C_code_hover_real.ipynb
// Recurrent policy: obs -> encoder -> GRU -> head -> action

#define NN_OBS_DIM    18
#define NN_ACT_DIM    6
#define NN_HIDDEN_DIM 64

// Zero the GRU hidden state. Call whenever the network is (re)activated,
// so no history from a previous flight leaks in.
void nn_reset_hidden(float* hidden);

// One inference step. `hidden` is read AND written: it carries the recurrent
// state and must persist across calls, at a fixed rate.
void nn_forward(const float* input, float* hidden, float* output);

#endif // NEURAL_NETWORK_H
