#ifndef CNN_ENCODER_H
#define CNN_ENCODER_H

#include <stdint.h>

// Generated by indiflight_module/Generate_C_code_navigate_split.ipynb
// COMPANION-COMPUTER half of the navigate_real policy: depth -> features.
// The recurrent half runs on the flight controller (see ../fc/).

#define CNN_RAW_H        48
#define CNN_RAW_W        64
#define CNN_POOL         4
#define CNN_IN_H         12
#define CNN_IN_W         16
#define CNN_FLAT_DIM     6144
#define CNN_FEATURE_DIM  64
#define CNN_BUF_MAX      6144
#define CNN_LEAKY_SLOPE  0.05f

#define CNN_FOV_DEG      80.0f   // horizontal
#define CNN_MIN_RANGE    0.3f   // below this the sensor reads 0
#define CNN_MAX_RANGE    8.0f   // no hit / saturated
#define CNN_QUANTIZE_DEPTH 1
#define CNN_QUANT_M      0.001f
#define CNN_NORM_NUM     3.0f   // v = NORM_NUM / clip(d, NORM_MIN, MAX) - NORM_OFF
#define CNN_NORM_MIN     0.3f
#define CNN_NORM_OFF     0.6f

// 1: a 0 / NaN depth pixel is treated as max range instead of "very close".
// 0 matches training, where 0 could only mean the blind zone. Real sensors
// also emit 0 for "no data", which then reads as an obstacle in your face.
#ifndef CNN_INVALID_IS_FAR
#define CNN_INVALID_IS_FAR 0
#endif

// Conv_0
#define L0_IH 12
#define L0_IW 16
#define L0_IC 1
#define L0_KH 2
#define L0_KW 2
#define L0_SH 2
#define L0_SW 2
#define L0_PT 0
#define L0_PL 0
#define L0_OH 6
#define L0_OW 8
#define L0_OC 32

// Conv_1
#define L1_IH 6
#define L1_IW 8
#define L1_IC 32
#define L1_KH 3
#define L1_KW 3
#define L1_SH 1
#define L1_SW 1
#define L1_PT 1
#define L1_PL 1
#define L1_OH 6
#define L1_OW 8
#define L1_OC 64

// Conv_2
#define L2_IH 6
#define L2_IW 8
#define L2_IC 64
#define L2_KH 3
#define L2_KW 3
#define L2_SH 1
#define L2_SW 1
#define L2_PT 1
#define L2_PL 1
#define L2_OH 6
#define L2_OW 8
#define L2_OC 128

// This half also gets compiled into the ground-station HITL renderer
// (hitl/src/encoder.cpp), which is C++, so the declarations carry linkage guards.
#ifdef __cplusplus
extern "C" {
#endif

// Depth preprocessing: sensor frame -> network input. The camera must already be
// cropped/resized to CNN_RAW_H x CNN_RAW_W covering CNN_FOV_DEG horizontally;
// a different FOV needs a crop, not a rescale.
void cnn_preprocess(const float* raw_depth_m, float* depth_in);

// Same, from the usual uint16 millimetre buffer. 0 means "invalid, or closer than
// the blind zone" -> see CNN_INVALID_IS_FAR.
void cnn_preprocess_u16(const uint16_t* raw_depth_mm, float* depth_in);

// CNN encoder: CNN_IN_H x CNN_IN_W normalized depth -> CNN_FEATURE_DIM features.
// Stateless: one frame in, one feature vector out.
void cnn_forward(const float* depth_in, float* features);

// preprocess + forward, for the common case.
void cnn_encode_frame(const uint16_t* raw_depth_mm, float* features);

// What the encoder produces for an empty scene (every pixel at max range). The FC
// carries a copy of this and uses it until the first vector arrives.
extern const float cnn_features_freespace[CNN_FEATURE_DIM];

#ifdef __cplusplus
}   // extern "C"
#endif

#endif // CNN_ENCODER_H
