#ifndef NEURAL_NETWORK_H
#define NEURAL_NETWORK_H

// Generated by indiflight_module/Generate_C_code_navigate_split.ipynb
// FLIGHT-CONTROLLER half of the navigate_real policy:
//   (img_feat from the companion, obs, hidden) -> action
// The CNN that produces img_feat runs off-board (see ../onboard/).

#define NN_OBS_DIM      16
#define NN_FEATURE_DIM  64   // width of the cut: what crosses from the companion
#define NN_HIDDEN_DIM   64
#define NN_ACT_DIM      4
#define NN_LEAKY_SLOPE  0.05f

// Zero the GRU hidden state. Call whenever the network is (re)activated,
// so no history from a previous flight leaks in.
void nn_reset_hidden(float* hidden);

// One inference step, at the control rate. `hidden` is read AND written: it
// carries the recurrent state and must persist across calls.
// `img_feat` is the latest NN_FEATURE_DIM vector from the companion. Holding
// the last one between camera frames is exactly what training did.
void nn_forward(const float* img_feat, const float* obs, float* hidden, float* output);

#endif // NEURAL_NETWORK_H
