### Basic Config

# MATEKSYS FC on CineRat 3inch Race Quad (and simuation model)
TARGET = STM32H743
EXTRA_FLAGS = -D'BUILD_KEY=4880cd41e59e44642e41c3f6344b3993' -D'RELEASE_NAME=4.4.2' -D'BOARD_NAME=MATEKH743' -D'MANUFACTURER_ID=MTKS' -DCLOUD_BUILD -DUSE_GYRO -DUSE_GYRO_SPI_ICM42605 -DUSE_GYRO_SPI_ICM42688P -DUSE_GYRO_SPI_MPU6000 -DUSE_GYRO_SPI_MPU6500 -DUSE_ACC -DUSE_ACC_SPI_ICM42605 -DUSE_ACC_SPI_ICM42688P -DUSE_ACC_SPI_MPU6000 -DUSE_ACC_SPI_MPU6500 -DUSE_DSHOT -DUSE_GPS -DUSE_LED_STRIP -DUSE_MAX7456 -DUSE_OSD -DUSE_OSD_HD -DUSE_OSD_SD -DUSE_PINIO -DUSE_BLACKBOX -DUSE_SDCARD -DUSE_SERIALRX -DUSE_SERIALRX_SBUS -DUSE_SERIALRX_CRSF -DUSE_TELEMETRY -DUSE_TELEMETRY_SMARTPORT
EXTRA_FLAGS += -DUSE_INDI_PROFILE_CINERAT

# Trashcan
#TARGET = STM32F411
#EXTRA_FLAGS = -D'BUILD_KEY=8af98ed87422efa3d2eff0e2e7a86e80' -D'RELEASE_NAME=4.4.2' -D'BOARD_NAME=CRAZYBEEF4FR' -D'MANUFACTURER_ID=HAMO' -DCLOUD_BUILD -DUSE_GYRO -DUSE_GYRO_SPI_ICM20689 -DUSE_GYRO_SPI_ICM42688P -DUSE_GYRO_SPI_MPU6000 -DUSE_ACC -DUSE_ACC_SPI_ICM20689 -DUSE_ACC_SPI_ICM42688P -DUSE_ACC_SPI_MPU6000 -DUSE_ACCGYRO_BMI270 -DUSE_DSHOT -DUSE_GPS -DUSE_LED_STRIP -DUSE_MAX7456 -DUSE_OSD -DUSE_OSD_HD -DUSE_OSD_SD -DUSE_PINIO -DUSE_RX_CC2500 -DUSE_RX_SPI -DUSE_SERIALRX -DUSE_SERIALRX_CRSF -DUSE_SERIALRX_DEFAULT -DUSE_SERIALRX_GHST -DUSE_SERIALRX_SBUS -DUSE_TELEMETRY -DUSE_TELEMETRY_CRSF -DUSE_TELEMETRY_GHST -DUSE_TELEMETRY_SMARTPORT -DUSE_VTX -DUSE_BLACKBOX
#EXTRA_FLAGS += -DUSE_INDI_PROFILE_TRASHCAN

# Robin and Stavrow
#TARGET = ???
#EXTRA_FLAGS = ???
#EXTRA_FLAGS += -DUSE_INDI_PROFILE_5INCHQUAD


### Extra Options

# indi config:
EXTRA_FLAGS += -DUSE_INDI -DUSE_OMEGA_DOT_FEEDBACK

# telemetry config:
EXTRA_FLAGS += -DUSE_TELEMETRY_PI -DPI_STATS -DPI_USE_PRINT_MSGS -DUSE_GPS_PI

# run EKF and whether to use it as vehicle state whenever position mode is active
# WARNING: USE_EKF_* are untested, and doubtful especially with inflight switching between POSITION and manual flying
EXTRA_FLAGS += -DUSE_EKF
#EXTRA_FLAGS += -DUSE_EKF_POSITION -DUSE_EKF_ATTITUDE

# higher level controllers, max bank override for pos controlled flight, and max downwards acceleration override
EXTRA_FLAGS += -DUSE_POS_CTL -DUSE_VEL_CTL
#EXTRA_FLAGS += -DUSE_TRAJECTORY_TRACKER

# DANGEROUS modes!!
EXTRA_FLAGS += -DUSE_THROW_TO_ARM
#EXTRA_FLAGS += -DUSE_CATAPULT -DUSE_LEARN_AFTER_CATAPULT

# DANGEROUS settings!!
#EXTRA_FLAGS += -DUSE_POS_YEET_GAINS
#EXTRA_FLAGS += -D'MAX_BANK_DEGREE_AUTO=180.f' -D'MAX_ACC_Z_POS=+20.f'

# Remove propellers: hardware in the loop simulation over UART
#EXTRA_FLAGS += -DHIL_BUILD
