########## TARGET CONFIG
TARGET = STM32H743
EXTRA_FLAGS = $(EXTRA_FLAGS_CMDLINE) -D'BUILD_KEY=4880cd41e59e44642e41c3f6344b3993' -D'RELEASE_NAME=4.4.2' -D'BOARD_NAME=MATEKH743' -D'MANUFACTURER_ID=MTKS' -DCLOUD_BUILD -DUSE_GYRO -DUSE_GYRO_SPI_ICM42605 -DUSE_GYRO_SPI_ICM42688P -DUSE_GYRO_SPI_MPU6000 -DUSE_GYRO_SPI_MPU6500 -DUSE_ACC -DUSE_ACC_SPI_ICM42605 -DUSE_ACC_SPI_ICM42688P -DUSE_ACC_SPI_MPU6000 -DUSE_ACC_SPI_MPU6500 -DUSE_DSHOT -DUSE_LED_STRIP -DUSE_MAX7456 -DUSE_OSD -DUSE_OSD_HD -DUSE_OSD_SD -DUSE_PINIO -DUSE_BLACKBOX -DUSE_SDCARD -DUSE_SERIALRX -DUSE_SERIALRX_SBUS -DUSE_SERIALRX_CRSF -DUSE_TELEMETRY -DUSE_TELEMETRY_SMARTPORT

########## FURTHER OPTIONS
# Developer options
#EXTRA_FLAGS += -DUSE_BENCHMARK -DUSE_STACK_CHECK

# indi config:
EXTRA_FLAGS += -DUSE_INDI

# telemetry config:
EXTRA_FLAGS += -DUSE_TELEMETRY -DUSE_TELEMETRY_PI -DPI_STATS -DPI_USE_PRINT_MSGS 

# position controller config
EXTRA_FLAGS += -DUSE_GPS              # display global position
#EXTRA_FLAGS += -DUSE_LOCAL_POSITION   # enable local position and controller

#EXTRA_FLAGS += -DUSE_LOCAL_POSITION_GPS # get local pos from gps, or...
#EXTRA_FLAGS += -DUSE_LOCAL_POSITION_PI  # ...from pi telemetry

EXTRA_FLAGS += -DUSE_POS_CTL -DUSE_GPS_PI

EXTRA_FLAGS += -DUSE_EKF

# higher level controllers / est
EXTRA_FLAGS += -DUSE_TRAJECTORY_TRACKER

# DANGEROUS modes!!
#EXTRA_FLAGS += -DUSE_ACCEL_RPM_FILTER   # defunc
EXTRA_FLAGS += -DUSE_THROW_TO_ARM # -DUSE_THROWING_WITHOUT_POSITION
EXTRA_FLAGS += -DUSE_CATAPULT
EXTRA_FLAGS += -DUSE_LEARNER
EXTRA_FLAGS += -DUSE_NN_CONTROL
#EXTRA_FLAGS += -DUSE_INERTIA_BY_THROWING
